# frozen_string_literal: true

ruby "3.1.0"

source "https://rubygems.org"

git_source(:github) { |repo| "git@github.com:#{repo}.git" }

gem "dotenv"
gem "verse-core", github: "verse-rb/verse-core", branch: "master"
gem "verse-http", path: "../.."
gem "verse-schema", github: "verse-rb/verse-schema", branch: "master"
gem "zeitwerk", require: false

gem "puma", ">= 6.3.1"
gem "rake"
